In [1]:
import h5py
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
h5_location = r'C:\Users\Jack\Documents\GitHub\FISH_Processing\Demos\DUSP1_DexTimeConcSweep_10nM_75min_041223\DUSP1_DexTimeConcSweep_10nM_75min_041223.h5'
h5_file = h5py.File(h5_location, 'r')

In [3]:
level = 1

def print_group(name, obj):
    # Calculate current level based on the name depth
    current_level = name.count('/')
    if current_level <= level:
        print("  " * current_level + f"- {name}")

h5_file.visititems(print_group)

- Analysis_demo_2024-11-17
  - Analysis_demo_2024-11-17/df_cellresults
  - Analysis_demo_2024-11-17/df_clusterresults
  - Analysis_demo_2024-11-17/df_spotresults
  - Analysis_demo_2024-11-17/parameters
- masks
- metadata
- raw_images
- {group_name}
  - {group_name}/{key}

In [4]:
pd.read_hdf(h5_location, key='Analysis_demo_2024-11-17/df_cellresults')

,cell_id,cell_area,nuc_area,nb_rna,nb_rna_in_nuc,nb_rna_out_nuc,nb_foci,nb_transcription_site,timepoint,fov,FISH_Channel
0,4,8893,8893,102,102,0,0,2,0,0,0
1,6,10358,10358,93,93,0,0,0,0,0,0
2,7,9573,9573,110,110,0,0,0,0,0,0
3,8,9634,9634,103,103,0,0,0,0,0,0
4,9,8176,8176,121,121,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
9,11,7861,7861,65,65,0,0,0,0,29,0
10,12,10169,10169,90,90,0,0,0,0,29,0
11,13,8678,8678,49,49,0,0,0,0,29,0
12,14,7896,7896,142,142,0,0,0,0,29,0
13,15,9606,9606,92,92,0,0,0,0,29,0

In [5]:
pd.read_hdf(h5_location, key='Analysis_demo_2024-11-17/df_clusterresults')

    z_px  y_px  x_px  nb_spots  cluster_index  timepoint  fov  FISH_Channel
0      8    24   161         4              0          0    0             0
1      8   532    38         4              1          0    0             0
2      6   168   242         5              2          0    0             0
3      7   215    50         7              3          0    0             0
4      6   337    83         5              4          0    0             0
..   ...   ...   ...       ...            ...        ...  ...           ...
14    12   280   386         4             14          0   29             0
15    10   481   485         5             15          0   29             0
16    13   198   533         4             16          0   29             0
17    12   285    65         4             17          0   29             0
18    13   448   438         4             18          0   29             0

[492 rows x 8 columns]